### ISSUE TITLE
Unhandled promise error when running "react-toolbox-themr"

### ISSUE THREAD

**Issue by dijs** [react-toolbox/react-toolbox-themr#11]
```UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Expected pseudo-class or pseudo-element```

Any ideas?

Or debugging tips?

**Comment by javivelasco** [comment]
Fixed!

**Comment by anri-asaturov** [comment]
Still get this with react-toolbox beta 5 and 6

**Comment by FDiskas** [comment]
and with react-toolbox beta 10
