### ISSUE TITLE
Paths are not properly resolved with Windows

### ISSUE THREAD

**Issue by stereokai** [react-toolbox/react-toolbox-themr#14]
After initializing an app using react-create-app, installing `react-toolbox` and `react-toolbox-themr ` and adding the script to package.json as so:
```
"toolbox": "react-toolbox-themr"
```

Calling `npm run toolbox` from the command prompt runs the script, but results in nothing. No content is added to `/public`. Using Windows 10.

Thanks!

**Comment by javivelasco** [comment]
Please try with the latest `beta.6`. If it stills fails with the latest patch and the latest beta, please reopen!

**Comment by stereokai** [comment]
With the latest react-toolbox and react-toolbox-themr from Github, I am getting the following error, although I followed exactly the directions shown in the GIF.
```
> react-toolbox-themr

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\...\node_modules\react-toolbox\lib\identifiers.js'
```

**Comment by stereokai** [comment]
@javivelasco I don't have the option of reopening, so I'm tagging you as  you requested to be notified :)

**Comment by javivelasco** [comment]
Damn Windows. I can't reproduce it locally, help needed for this :(

**Comment by stereokai** [comment]
@javivelasco tell me where to look and what to look for and I'll look into this :)

**Comment by mattzuba** [comment]
I'm running this with Win10 and beta.6 and I haven't had any issues.  @stereokai - What does the `reactToolbox` section of your package.json file look like?

**Comment by pekkah** [comment]
@stereokai check your `src/toolbox` folder if you haven't overridden the output in `packages.json/reactToolbox`

**Comment by javivelasco** [comment]
It looks like this was generated by something else and can be closed! Maybe it's an issue with an specific Windows version or something? Please reopen if the problem persists!

**Comment by anri-asaturov** [comment]
Got it for osx, no idea why yet 👯

**Comment by anri-asaturov** [comment]
Ok, cross that ^ the issue was with 2 package json electron repo and somehow missing node_nodules in /app folder
