### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by waclock** [react-toolbox/react-toolbox-themr#15]
Hello,

I'm trying to install react-toolbox-themr, however I'm getting an error when trying to add it through NPM. I've installed react-toolbox@2.0.0-beta.6, but when I try adding react-toolbox-themr I get the following message

```
npm install react-toolbox-themr --save
├── UNMET PEER DEPENDENCY react-toolbox@2.0.0-beta.6
└── react-toolbox-themr@1.0.2

npm WARN react-toolbox-themr@1.0.2 requires a peer of react-toolbox@^2.0.0 but none was installed.
```

React-toolbox is correctly installed, I did a cache clean, installed everything from 0, but I still get this message. Any suggestions?

Thanks!

**Comment by javivelasco** [comment]
That error is shown when you install `react-toolbox-themr` alone without `react-toolbox`. It looks more like a local issue. Try out with `yarn` or something :S

**Comment by waclock** [comment]
When I try installing everything from scratch with yarn I get the following warning:

`warning "react-toolbox-themr@1.0.2" has incorrect peer dependency "react-toolbox@^2.0.0".`

Also, This is what my package.json looks like 

```
...
  "dependencies": {
    "babel-runtime": "^6.22.0",
    "classnames": "^2.2.5",
    "material-ui": "^0.16.7",
    "normalize.css": "^4.2.0",
    "ramda": "^0.23.0",
    "react": "^15.4.2",
    "react-css-themr": "^1.7.2",
    "react-dom": "^15.4.2",
    "react-fontawesome": "^1.5.0",
    "react-redux": "^5.0.2",
    "react-router": "^3.0.2",
    "react-router-redux": "^4.0.7",
    "react-tap-event-plugin": "^2.0.1",
    "react-toolbox": "^2.0.0-beta.6",
    "react-toolbox-themr": "^1.0.2",
    "redux": "^3.6.0",
    "redux-auth-wrapper": "^0.10.0",
    "redux-devtools": "^3.3.2",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.2.0",
    "semantic-ui-css": "^2.2.4",
    "semantic-ui-react": "^0.64.3"
  },
...
```

Right now following the instructions of the GIF, I'm getting the following error (if I don't take in consideration the warning while installing the themr)

`Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird`

Last but not least, when I run "yarn run toolbox" the files theme.css and theme.js are generated in src/toolbox and not react-toolbox. I've obviously adapted the routes when I import these files, but I do not understand why this happens compared to the gif.

**Comment by javivelasco** [comment]
Sorry, the gif has the wrong paths, I have to update it! Maybe the warning is just because the current version is a beta and it does not match properly as a peer, but it's ok. This will be solved as we release a final version.

What I'm not sure is about the error you are getting with composition. It's an error or a warning? Is it generating the css and js modules?

**Comment by abumalick** [comment]
I had the same problem, installing `react-toolbox` manually fixed the bug.

Can you add instructions in README  ?

` yarn add react-toolbox@2.0.0-beta.6`

**Comment by javivelasco** [comment]
If you think it should be added to the README I'd accept a PR for it :)
For me it's pretty obvious that react-toolbox should be added manually but if it's not the case for everybody I agree we should add it

**Comment by tortilaman** [comment]
I've been running into this issue when react-toolbox is required in another package and you yarn the "parent" package that's dependant on it.
