### ISSUE TITLE
Put example source code in project

### ISSUE THREAD

**Issue by alaindresse** [react-toolbox/react-toolbox-themr#18]
Hi,

I couldn't manage to reproduce what is displayed in the animated gif: I get the button, but it is not styled.

Would it be possible to put the simple react-create-app example in a repo ?

Many thanks,
Alain

**Comment by prabhakhar** [comment]
@alaindresse As specified in Usage section, https://github.com/react-toolbox/react-toolbox-themr#usage, add configuration to package.json, like,

```
"reactToolbox": {
  "include": [
    "BUTTON",
    "DATE_PICKER"
  ],
  "output": "assets/react-toolbox"
}
```

and run "yarn run toolbox".

**Comment by alaindresse** [comment]
Thanks @prabhakhar,

but it didn't really work. I uploaded my test here: https://github.com/alaindresse/test-react-toolbox.

See the gif below. The ripple is styled in the button, but not the button. What am I doing wrong ?

Many thanks,
Alain

![test-toolbox](https://cloud.githubusercontent.com/assets/1415531/22612759/1a996ba4-ea73-11e6-868e-806de295c835.gif)

**Comment by prabhakhar** [comment]
interesting.... try cloning this repo.. "git clone git@github.com:prabhakhar/wormhole.git"
and execute the commands as shown and let me know.

```
in tmp/
› git clone git@github.com:prabhakhar/wormhole.git
Cloning into 'wormhole'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 19 (delta 0), reused 19 (delta 0), pack-reused 0
Receiving objects: 100% (19/19), 86.58 KiB | 0 bytes/s, done.

in tmp/
› cd wormhole

in wormhole/ on master
› yarn install
yarn install v0.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-toolbox-themr@1.0.2" has incorrect peer dependency "react-toolbox@^2.0.0".
warning "eslint-plugin-babel@4.0.1" has unmet peer dependency "eslint@>=3.0.0".
[4/4] 📃  Building fresh packages...
✨  Done in 11.45s.

in wormhole/ on master
› yarn start
```

**Comment by alaindresse** [comment]
Thanks !
Works nicely...
Will take a look at the differences with my environment.

Alain

**Comment by alaindresse** [comment]
Got it ! Many thanks!
Wouldn't have found it without wormhole...

The issue was

`import {Button} from 'react-toolbox/lib/button/Button';`

instead of 

`import Button from 'react-toolbox/lib/button/Button';`
