### ISSUE TITLE
Installing react-toolbox-themr

### ISSUE THREAD

**Issue by Cloudilicious** [react-toolbox/react-toolbox-themr#21]
Hi there,

After initialising an app using react-create-app and installing react-toolbox, I am getting the following error message when trying to install react-toolbox-themr:

```react-toolbox-themr@1.0.2 requires a peer of react-toolbox@^2.0.0 but none was installed```

However, I have the following in my package.json:
```"react-toolbox": "^2.0.0-beta.6"```

Any advice would be much appreciated.
Thank you!

**Comment by ingro** [comment]
Are you still using npm@2.x? That error should become a simple warning with npm@3.x.

**Comment by Cloudilicious** [comment]
Thanks for your reply ingro.
You were right. I was using npm 3.10.9 so I checked my node-modules folder and the themr files were there.

**Comment by javivelasco** [comment]
Cool!
