### ISSUE TITLE
Can't import Checkbox

### ISSUE THREAD

**Issue by ralvs** [react-toolbox/react-toolbox-themr#26]
`Failed to compile.`
`Error in ./~/react-toolbox/lib/checkbox/Checkbox.js`
`Module not found: 'react-style-proptype' in`
`/Volumes/stuff/reactSpher.toolbox/node_modules/react-toolbox/lib/checkbox`

`@ ./~/react-toolbox/lib/checkbox/Checkbox.js 20:26-57`

I'm getting this error when try to import Checkbox or Table (that uses checkbox).
Other components are working fine.

My package.json

`  "reactToolbox": {
    "include": [
			"CHECKBOX",
      "AUTOCOMPLETE",
      "BUTTON",
      "CARD",
      "DATE_PICKER",
      "DIALOG",
      "DRAWER",
      "DROPDOWN",
      "INPUT",
      "LAYOUT",
      "LINK",
      "LIST",
      "MENU",
      "NAVIGATION",
      "OVERLAY",
      "PROGRESS_BAR",
      "RADIO",
      "RIPPLE",
      "SLIDER",
      "SNACKBAR",
      "SWITCH",
      "TABLE",
      "TABS",
      "TOOLTIP"
    ],
    "output": "src/styles/react-toolbox"
  },`

**Comment by lc1983** [comment]
Try add react-style-proptype module: yarn add react-style-proptype.

**Comment by ralvs** [comment]
Awesome! Checkbox is working!
But I still have problems with table.

`Warning: Unknown props `model`, `source` on <table> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by javivelasco** [comment]
Sorry about it @ralves09 the deployed documentation is for the 1.x version. Please check the component READMEs in the `dev` branch to see the current docs for `Table`

**Comment by ralvs** [comment]
Nice! It's working now!
Thanks!
