### ISSUE TITLE
List Element Ripple bug

### ISSUE THREAD

**Issue by liangchunn** [react-toolbox/react-toolbox-themr#29]
![2017-02-22 20_50_43](https://cloud.githubusercontent.com/assets/18398406/23229479/c2924890-f940-11e6-960a-18a0875d989a.gif)

Apparently the ripples aren't appearing on the right places. 
Am I doing something wrong?

**Comment by supirman** [comment]
This happen to me too. I use `create-react-app` to create the project. 
Ripple only working rigth inside single ListItem in the middle of the Lisy, other ListItem ripple center is on the working list item but x-axis follow mouse posistion.

**Comment by daver182** [comment]
This is related with a bug in react-toolbox, in beta-7 is already resolved, [Issue](https://github.com/react-toolbox/react-toolbox/issues/1205)
