### ISSUE TITLE
TypeError: Cannot read property 'stats' of undefined in caniuse

### ISSUE THREAD

**Issue by sosaucily** [react-toolbox/react-toolbox-themr#36]
I was getting this error because react-boilerplate gave me an older version of caniuse-db.

Had to `yarn remove xxx` on react-toolbox-themr, and css-loader, then do a yarn install.

Check you have version 1.0.3000063x or later of caniuse-db in your yarn.lock file.

If not, remove packages, or reinstall everything.

The issue is that there are some older versions of caniuse-db that technically meet the dependency needs of these projects, but are missing some attribute fields.  More info here:
https://github.com/MoOx/postcss-cssnext/pull/359

**Comment by allenwalker3** [comment]
I did 'npm remove caniuse-db' then 'npm install caniuse-db'  , 

after that 'yarn run toolbox' worked
