### ISSUE TITLE
External config properties ignored

### ISSUE THREAD

**Issue by anri-asaturov** [react-toolbox/react-toolbox-themr#5]
So if you specify external config file via `--config rtb.json`,
all is good up until `src/configure.js/getConfig()` executes, I don't know ramda and didn't debug further, but `getConfig()` returns configuration where all properties from external file are replaced with default ones.

**Comment by javivelasco** [comment]
Actually the `const inputOptions = R.merge(C.DEFAULT_OPTIONS, filterInput(config))` is replacing the defaults with external. Maybe there is something missing, I'm trying out asap

**Comment by anri-asaturov** [comment]
Maybe filterInput doesn't do what it's supposed to
