### ISSUE TITLE
Failed to compile. Module build failed.

### ISSUE THREAD

**Issue by michaelpumo** [react-toolbox/react-toolbox-themr#8]
I get the following error when trying to use a `<Button />` component. This happens also for any other component that I try.

```
Failed to compile.

Error in ./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".button", ".button" is weird
    at Array.map (native)
 @ ./~/react-toolbox/lib/button/theme.css 4:14-120 13:2-17:4 14:20-126
```

I am using `react-toolbox-themr` within a `create-react-app`.

My example code is:

```
import React, { Component } from 'react';
import theme from '../assets/react-toolbox/theme';
import ThemeProvider from 'react-toolbox/lib/ThemeProvider';
import { Button } from 'react-toolbox/lib/button';

class App extends Component {
  render() {
    return (
      <ThemeProvider theme={theme}>
        <Button icon="bookmark" label="Test" raised primary />
      </ThemeProvider>
    );
  }
}

export default App;
```

I can't really understand where I am going wrong. I have followed the guide as specified here:
https://github.com/react-toolbox/react-toolbox-themr

In my `package.json` I have:

```
  "reactToolbox": {
    "include": [
      "BUTTON"
    ],
    "customProperties": {
      "animation-duration": "0.3s",
      "color-accent": "var(--palette-pink-a200)",
      "color-accent-dark": "var(--palette-pink-700)",
      "color-primary-contrast": "var(--color-dark-contrast)",
      "color-accent-contrast": "var(--color-dark-contrast)"
    },
    "output": "assets/react-toolbox"
  },

```

I'm using:

```
"react-toolbox": "2.0.0-beta.4",
"react-toolbox-themr": "^1.0.1"
```

Any ideas at all? Is it something I'm doing wrong?

Thanks!

PS - I'm on Mac OS.

**Comment by michaelpumo** [comment]
Okay, I have this solved. It was an error on my part, as it wasn't immediately clear to me from the docs that I needed to import my button as:

`import Button from 'react-toolbox/lib/button/Button';`

And **not**:

`import { Button } from 'react-toolbox/lib/button';`

All working now. 

If you're using `create-react-app`, you need to have the following minimal setup:

**index.js**

```
import React from 'react';
import ReactDOM from 'react-dom';
import ThemeProvider from 'react-toolbox/lib/ThemeProvider';
import theme from '../assets/react-toolbox/theme';
import '../assets/react-toolbox/theme.css';
import App from './App';

ReactDOM.render(
  <ThemeProvider theme={theme}>
    <App />
  </ThemeProvider>,
  document.getElementById('root')
);
```

**App.js**

```
import React, { Component } from 'react';
import Button from 'react-toolbox/lib/button/Button';

class App extends Component {
  render() {
    return (
      <div>
        <Button label="Hello world!" raised primary />
      </div>
    );
  }
}

export default App;
```

Maybe we could include this code in the README file? It might help someone like me. I only noticed because I was eagle-eyeing your very speedy screen capture.

Thanks!

**Comment by willianribeiro** [comment]
Thank You, @michaelpumo! On documentation it's not explicit its needed import `assets/react-toolbox/theme.css`. Your comment help me a lot :+1:

**Comment by javivelasco** [comment]
Thanks!
